### ISSUE TITLE
Support "vivid" vs "natural"

### ISSUE THREAD

**Issue by darkvertex** [Blizarre/microdalle#3]
https://help.openai.com/en/articles/8555480-dall-e-3-api

There's a "style" optional param that defaults to "vivid" but can also be "natural" and it greatly changes the image.

Would be nice if it existed as a dropdown option. Might make a PR for it when I have some free time.

**Comment by Blizarre** [comment]
Hi, thanks for your suggestion, 
I was hesitant to add it originally because I worried that the interface would become too cluttered, but we all love to have options....
I will add it with a toggle to only show it (and the generated prompt) if required.

**Comment by Blizarre** [comment]
I just added the feature, and a "toggle" button to hide the settings.
I also save the settings to local storage,  so that whenever you come back to the page, or reload, the settings are kept.
I added that feature because it was inconvenient to have the settings reset every time when they were hidden.
Does that solve your issue?

**Comment by darkvertex** [comment]
Does the job. Thank you.
